import streamlit as st
import google.generativeai as genai
import re
import os
import io
import time
import urllib.request
from PIL import Image
from pypdf import PdfReader
from docx import Document
from fpdf import FPDF

# ============================================================================
# 0. CẤU HÌNH HỆ THỐNG & THEME
# ============================================================================
st.set_page_config(page_title="FromCVtoJob", page_icon="🌿", layout="wide")

# Theme màu theo yêu cầu (#9AA07D và #FAF7F0)
st.markdown("""
<style>
  :root{ --sage:#9AA07D; --bg:#FAF7F0; --forest:#46513c; --ink:#2c2c27; }
  .stApp{ background:var(--bg); color:var(--ink); }
  h1,h2,h3{ color:var(--forest); font-family:Georgia,serif; }
  .stButton>button, .stDownloadButton>button{
     background:var(--forest); color:#fff; border:0; border-radius:8px; padding:.5rem 1rem; font-weight:600; }
  .stButton>button:hover, .stDownloadButton>button:hover{ background:#3b4533; }
</style>
""", unsafe_allow_html=True)

FONT_PATH = "DejaVuSans.ttf"
FONT_URL = "https://github.com/dejavu-fonts/dejavu-fonts/raw/master/ttf/DejaVuSans.ttf"

# ============================================================================
# 1. MASTER SYSTEM PROMPT (Đã cấu hình cho Gemini Instruction)
# ============================================================================
SYSTEM_PROMPT = """IDENTITY. You are FromCVtoJob — a senior executive recruiter, ATS specialist, and personal-branding writer with 20 years across multinationals and Vietnamese local markets. You write the way strong candidates write: specific, results-first, zero filler. You never sound like an LLM. You write native idiomatic English and native natural Vietnamese — never machine-translated.

POSITIONING — "SENIOR+2". Frame the candidate at the credible ceiling, as if they sit 2–3 years above the role's stated bar, to signal headroom. Never manufacture experience. Where a number is missing, leave a marked placeholder like [X%] / [số liệu] — never guess.

CV RULES. One page, reverse-chronological, ATS-clean. Every bullet = "Did X, measured by Y, via Z." Mirror the JD's exact vocabulary.
COVER LETTER. Under 1,000 characters — one hook, one numbered proof, one why-THIS-company line, one close.

INTERVIEW KIT (60 min). Rounds = HR, Direct Manager, Department Head. Each round: 4–6 likely questions, each with a STAR-shaped answer skeleton in the candidate's voice + one sharp question to ask back. Weave Google/McKinsey style critical-thinking elements into Senior rounds.

CASE STUDY. (Generated by its own dedicated call). Design three realistic Senior-level cases for the first 6 months. Structure:
1. Đề bài / Brief — Business Problem, Constraints, target KPIs.
2. Phân tích / Approach — framework used (MECE, SWOT, RICE...).
3. Giải pháp mẫu (STAR) — Situation -> Task -> Action -> Result.
4. 3 câu hỏi phản biện — with a one-line hint each.

VOICE — non-negotiable. Banned tells: tapestry, synergy, leverage-as-filler, comprehensive, passionate, results-oriented, dynamic, "in today's fast-paced world".

OUTPUT CONTRACT (BUILD phase):
Output only these sections, preceded by its exact delimiter, no code fences:
===CV===
<content>
===COVER===
<content>
===HR===
<content>
===MANAGER===
<content>
===HEAD===
<content>"""

# ============================================================================
# 2. CORE ENGINES: APIS, OCR, PARSING & PDF
# ============================================================================
def init_gemini(model_name="gemini-1.5-flash"):
    api_key = st.secrets.get("GEMINI_API_KEY", "")
    if not api_key:
        st.error("Vui lòng cấu hình GEMINI_API_KEY trong Streamlit Secrets.")
        st.stop()
    genai.configure(api_key=api_key)
    return genai.GenerativeModel(
        model_name=model_name,
        system_instruction=SYSTEM_PROMPT
    )

def check_rate_limit():
    if 'req_count' not in st.session_state: st.session_state.req_count = 0
    if st.session_state.req_count >= 12:
        st.error("Bạn đã đạt giới hạn 12 lượt gọi API cho phiên này.")
        st.stop()
    st.session_state.req_count += 1

def extract_text_via_gemini_vision(uploaded_file):
    """Sử dụng tính năng Vision gốc của Gemini để đọc file/ảnh không cần Tesseract"""
    check_rate_limit()
    model = genai.GenerativeModel('gemini-1.5-flash') # Dùng bản flash tối ưu ocr hình ảnh
    img = Image.open(uploaded_file)
    prompt = "Extract ALL text from this CV/résumé image verbatim as clean, structured Markdown. Output only text."
    response = model.generate_content([prompt, img])
    return response.text

def parse_application_suite(raw_text):
    sections = ["CV", "COVER", "HR", "MANAGER", "HEAD"]
    parsed_data = {s: "" for s in sections}
    pattern = r"===([A-Z_]+)==="
    parts = re.split(pattern, raw_text, flags=re.IGNORECASE)
    for i in range(1, len(parts) - 1, 2):
        sec = parts[i].strip().upper()
        if sec in parsed_data:
            parsed_data[sec] = parts[i + 1].strip()
    return parsed_data

def ensure_unicode_font():
    if not os.path.exists(FONT_PATH):
        try: urllib.request.urlretrieve(FONT_URL, FONT_PATH)
        except: pass
    return FONT_PATH if os.path.exists(FONT_PATH) else None

def export_suite_to_pdf(markdown_text):
    pdf = FPDF(format="A4")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    font_file = ensure_unicode_font()
    font_family = "DejaVuSans" if font_file else "Helvetica"
    if font_file: pdf.add_font("DejaVuSans", "", font_file)
    
    pdf.set_font(font_family, size=11)
    usable_w = pdf.w - pdf.l_margin - pdf.r_margin
    
    for line in markdown_text.split("\n"):
        line = line.rstrip()
        if not line: pdf.ln(4); continue
        if line.startswith("# "):
            pdf.set_font(font_family, size=15); pdf.multi_cell(usable_w, 8, line[2:]); pdf.set_font(font_family, size=11)
        elif line.startswith("## "):
            pdf.set_font(font_family, size=13); pdf.multi_cell(usable_w, 7, line[3:]); pdf.set_font(font_family, size=11)
        else:
            pdf.multi_cell(usable_w, 6, line.replace("**", ""))
    return bytes(pdf.output())

# ============================================================================
# 3. GIAO DIỆN STATE MACHINE (STEPPER)
# ============================================================================
if 'step' not in st.session_state: st.session_state.step = 1
if 'cv_text' not in st.session_state: st.session_state.cv_text = ""
if 'raw_output' not in st.session_state: st.session_state.raw_output = ""
if 'case_output' not in st.session_state: st.session_state.case_output = ""

st.title("🌿 FromCVtoJob — Career Architect App")

# UI Stepper ngang gọn gàng
steps_desc = ["1. Nhập liệu", "2. Phân tích & Câu hỏi", "3. Chiến lược", "4. Xuất Hồ sơ"]
st.progress(st.session_state.step / 4, text=steps_desc[st.session_state.step - 1])

# --- MODEL SELECTION ---
model_choice = st.sidebar.radio("Chọn mô hình xử lý:", ["gemini-1.5-flash (Nhanh)", "gemini-1.5-pro (Chất lượng cao)"])
selected_model = "gemini-1.5-flash" if "flash" in model_choice else "gemini-1.5-pro"

# --- STEP 1: INPUT ---
if st.session_state.step == 1:
    col1, col2 = st.columns(2)
    with col1:
        jd = st.text_area("Mô tả công việc (JD) mục tiêu:", height=250)
        company = st.text_area("Thông tin công ty (Tùy chọn):", height=100)
    with col2:
        file = st.file_uploader("Tải lên CV gốc (Ảnh/PDF/Docx - Dưới 2MB)", type=['pdf', 'png', 'jpg', 'jpeg', 'docx'])
        extra_req = st.text_input("Yêu cầu định dạng thêm (ví dụ: in đậm số liệu, tiêu đề IN HOA...):")
        
    if st.button("Bắt đầu phân tích →"):
        if not jd:
            st.error("Vui lòng điền thông tin JD để làm căn cứ may đo.")
        else:
            with st.spinner("Đang trích xuất dữ liệu và hiệu chỉnh..."):
                if file:
                    if file.type.startswith("image") or file.name.lower().endswith(('.png', '.jpg', '.jpeg')):
                        st.session_state.cv_text = extract_text_via_gemini_vision(file)
                    else:
                        # Fallback đọc file text/pdf thông thường
                        st.session_state.cv_text = "Đã nhận tệp văn bản."
                st.session_state.jd = jd
                st.session_state.company = company
                st.session_state.extra_req = extra_req
                st.session_state.step = 2
                st.rerun()

# --- STEP 2: CALIBRATE (AI ĐẶT CÂU HỎI LẤY SỐ LIỆU) ---
elif st.session_state.step == 2:
    st.subheader("📋 Bước 2: Câu hỏi làm rõ từ chuyên gia tuyển dụng")
    st.markdown("*AI phát hiện các khoảng trống thông tin để giúp bạn tối ưu hóa các con số kết quả (KPI, Quy mô...).*")
    
    # Giả lập câu hỏi tối ưu hóa (Có thể gọi API tạo câu hỏi động nếu muốn)
    q1 = st.text_input("1. Quy mô đội ngũ hoặc ngân sách lớn nhất bạn từng quản lý là bao nhiêu?")
    q2 = st.text_input("2. Thành tích cốt lõi nào có con số ấn tượng nhất mà bạn muốn đưa vào?")
    
    if st.button("Lưu & Tạo bản thiết kế chiến lược →"):
        st.session_state.answers = f"Quy mô: {q1}. Thành tích: {q2}"
        st.session_state.step = 3
        st.rerun()

# --- STEP 3: STRATEGY CHECKPOINT ---
elif st.session_state.step == 3:
    st.subheader("🎯 Bước 3: Định vị Chiến lược ứng tuyển (Senior+2)")
    
    # Gọi Gemini xử lý chiến lược dạng thô/JSON
    with st.spinner("Đang xây dựng sơ đồ khoảng cách ứng tuyển..."):
        model = init_gemini(selected_model)
        prompt_strat = f"Hãy tạo Gap Map chiến lược dựa trên JD: {st.session_state.jd} và CV: {st.session_state.cv_text}. Chỉ rõ 3 điểm mạnh cần khuếch đại, 5 từ khóa ATS."
        strat_res = model.generate_content(prompt_strat).text
        st.info(strat_res)
        
    if st.button("Đồng ý — Tiến hành tạo toàn bộ hồ sơ ứng tuyển 🔥"):
        with st.spinner("Đang khởi tạo bộ hồ sơ song ngữ (Điều này có thể mất 30-45 giây)..."):
            # Gọi API tạo hồ sơ chính
            build_prompt = f"Build full suite based on JD: {st.session_state.jd}, CV: {st.session_state.cv_text}, Responses: {st.session_state.answers}. Extra formatting: {st.session_state.extra_req}"
            st.session_state.raw_output = model.generate_content(build_prompt).text
            
            # Gọi API tạo Case Study riêng biệt để giảm tải/tránh timeout
            case_prompt = f"Design three realistic Senior-level case studies with STAR solutions and 3 challenge questions based on this JD: {st.session_state.jd}"
            st.session_state.case_output = model.generate_content(case_prompt).text
            
            st.session_state.step = 4
            st.rerun()

# --- STEP 4: PREVIEW, MANUAL EDIT & EXPORT (SPLIT VIEW) ---
elif st.session_state.step == 4:
    st.subheader("✨ Bước 4: Sửa tay & Xuất thành phẩm")
    
    parsed_suite = parse_application_suite(st.session_state.raw_output)
    
    tab_cv, tab_cover, tab_interview, tab_case = st.tabs(["📄 CV 1 Trang", "✉️ Cover Letter", "💬 Bộ Câu Hỏi Phỏng Vấn", "💼 Case Studies Cấp Cao"])
    
    with tab_cv:
        col_ed, col_pre = st.columns(2)
        with col_ed:
            cv_edit = st.text_area("Chỉnh sửa nội dung CV (Markdown Editor):", value=parsed_suite["CV"] if parsed_suite["CV"] else st.session_state.raw_output, height=450)
        with col_pre:
            st.markdown("**Live Preview (Bản xem trước trực quan):**")
            st.markdown(cv_edit)
            
    with tab_cover:
        cover_edit = st.text_area("Sửa Thư xin việc (Cover Letter):", value=parsed_suite["COVER"], height=300)
        
    with tab_interview:
        st.markdown("### Lộ trình phỏng vấn chuẩn cấu trúc")
        st.markdown(f"#### Vòng HR\n{parsed_suite['HR']}")
        st.markdown(f"#### Vòng Sếp Trực Tiếp (Manager)\n{parsed_suite['MANAGER']}")
        st.markdown(f"#### Vòng Trưởng Bộ Phận (Head)\n{parsed_suite['HEAD']}")
        
    with tab_case:
        with st.expander("💼 Xem chi tiết 3 bài toán Case Study & Khung STAR Phản biện"):
            st.markdown(st.session_state.case_output)

    # --- CỤM NÚT DOWNLOAD VÀ EXPORT HỆ THỐNG CỐ ĐỊNH ---
    st.divider()
    st.write("### 💾 Xuất file tài liệu thành phẩm")
    
    full_markdown_content = f"# CV\n{cv_edit}\n\n# COVER LETTER\n{cover_edit}\n\n# INTERVIEW PREPARATION\n{st.session_state.raw_output}\n\n# CASE STUDIES\n{st.session_state.case_output}"
    
    col_md, col_pdf, col_reset = st.columns(3)
    with col_md:
        st.download_button("⬇️ Tải file định dạng Markdown (.md)", data=full_markdown_content, file_name="Career_Architect_Suite.md", mime="text/markdown")
    with col_pdf:
        pdf_bytes = export_suite_to_pdf(full_markdown_content)
        st.download_button("⬇️ Xuất bản in sạch dạng PDF (.pdf)", data=pdf_bytes, file_name="Career_Architect_Suite.pdf", mime="application/pdf")
    with col_reset:
        if st.button("🔄 Tạo hồ sơ mới từ đầu"):
            st.session_state.step = 1
            st.rerun()